### ISSUE TITLE
Installation tutorial is not working

### ISSUE THREAD

**Issue by jahernandezr1** [EuropeanRoverChallenge/ERC-Remote-Navigation-Sim#10]
Hello, I'm trying to install "ERC Remote Navigation Simulation" doing the step-by-step guide but, I got these errors, in both errors its seems to be missing "leo-description" files. What should I do?

![problem1](https://user-images.githubusercontent.com/82291476/121974870-fb733100-cd45-11eb-9d1b-2b65e7c59f82.png)
![problem2](https://user-images.githubusercontent.com/82291476/121974868-fada9a80-cd45-11eb-997b-fd88425519ce.png)

**Comment by bjsowa** [comment]
Make sure you do:
```
sudo apt update
```
before running `rosdep install`

**Comment by bjsowa** [comment]
If you get `EXPKEYSIG` error when running `sudo apt update`, you need to do:
```
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
```

**Comment by jahernandezr1** [comment]
It's already running, thanks!
