### ISSUE TITLE
Unable to run clean docker container

### ISSUE THREAD

**Issue by facorazza** [EuropeanRoverChallenge/ERC-Remote-Navigation-Sim#6]
We are trying to setup the docker container but even without any customization we get the following error:
```
xcb_connection_has_error() returned true
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
[ INFO] [1621628661.725817494]: waitForService: Service [/gazebo/set_physics_properties] is now available.
process[odom_compat_node-9]: started with pid [227]
[ INFO] [1621628661.752000601]: Physics dynamic reconfigure ready.
process[zed2_imu_transform_publisher-10]: started with pid [291]
process[zed2_imu_transform_broadcaster-11]: started with pid [294]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)
[gazebo_gui-3] process has died [pid 65, exit code 134, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/85b1f838-ba72-11eb-82c0-0242ac110002/gazebo_gui-3.log].
log file: /root/.ros/log/85b1f838-ba72-11eb-82c0-0242ac110002/gazebo_gui-3*.log
```

We are running the docker container with:
`docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY --name erc_sim --gpus all -e NVIDIA_DRIVER_CAPABILITIES=all erc_navigation_sim`
with and without `--privileged`

**Comment by bjsowa** [comment]
Please paste the complete output of the `docker run` command and answer those questions:
1. What OS are you using?
2. Did you pull the image from container registry or did you build it yourself?
3. Did you run `xhost +local:root` before running the container?
4. Have you installed the [Nvidia Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#install-guide)?

**Comment by facorazza** [comment]
Thanks we forgot to run `xhost +local:root`
