### ISSUE TITLE
Both docker and my own build give this error.

### ISSUE THREAD

**Issue by canyagmur** [EuropeanRoverChallenge/ERC-Remote-Navigation-Sim#7]
![error](https://user-images.githubusercontent.com/57918657/119223887-917bb900-bb04-11eb-9f42-1bca20ca6c87.png)

This is what I get when I am trying to launch leo_gazebo.launch.

**Comment by vitlinda** [comment]
I solved deleting the rosdep default sources list file
$ sudo rm /etc/ros/rosdep/sources.list.d/20-default.list
and then following again the Building section from the README

**Comment by canyagmur** [comment]
> I solved deleting the rosdep default sources list file
> $ sudo rm /etc/ros/rosdep/sources.list.d/20-default.list
> and then following again the Building section from the README

Thank you for your answer. It worked!
