### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by GiuliaB97** [EuropeanRoverChallenge/ERC-Remote-Navigation-Sim#8]
**Expected Behavior**
I should be able to build and execute the Docker container with the commands you wrote.

**Observed Behavior**
The build fails:

```shell_session
W: GPG error: http://packages.ros.org/ros/ubuntu bionic InRelease: The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics <info@osrfoundation.org>
E: The repository 'http://packages.ros.org/ros/ubuntu bionic InRelease' is not signed.
The command '/bin/sh -c apt-get update && apt-get -y upgrade && apt-get install -y     python-rosdep     python-catkin-tools   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Steps to reproduce**
```shell_session
 docker build -t erc_navigation_sim .
 ```

**Your Environment**
- Ubuntu 18.04

**Comment by bjsowa** [comment]
This is related to the [ROS GPG Expiration Incident](https://discourse.ros.org/t/ros-gpg-key-expiration-incident/20669) which resulted in faulty base ROS images.
The fix in docker-library/official-images#10272 has been merged recently so you can try to rebuild the image now.

**Comment by GiuliaB97** [comment]
Thanks, the previous error seems to be fixed; I can build the Dockerfile, however now when I try to run it, the following error is shown in the shell:
```shell_session
RLException: [leo_marsyard.launch] is neither a launch file in package [leo_erc_gazebo] nor is [leo_erc_gazebo] a launch file name
The traceback for the exception was written to the log file
```

**Comment by bjsowa** [comment]
Did you clone this repository with `--recurse-submodules` ? If not, do:
```
git submodule update --init
```
and rebuild the image.

**Comment by GiuliaB97** [comment]
I think so, in any case if I try to execute your command before re-building the Dockerfile, the building process works fine, however when I run the containger I get the following error: 
```shell_session
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "source": executable file not found in $PATH: unknown.
ERRO[0003] error waiting for container: context canceled 
```
On the other hand if I try to re-clone the repository to be sure to add the correct submodules with the following command:
```shell_session
git clone --recurse-submodules https://github.com/EuropeanRoverChallenge/ERC-Remote-Navigation-Sim.git

```
I get again the error on the GPG key.

**Comment by bjsowa** [comment]
Try the `docker build` command with `--pull` and `--no-cache` options

**Comment by GiuliaB97** [comment]
I have already tried the following command:
```shell_session
docker build --no-cache -t erc_navigation_sim .
```
However i still get the same error.

I also tried to reboot the system; doing so the new repository (the one I cloned this morning with the `--recurse-submodules` option) now returns the same error of the previous one.

**Comment by bjsowa** [comment]
Try to also add the `--pull` option.

**Comment by GiuliaB97** [comment]
Sorry I forgot to tell you; also running ` docker build --pull --no-cache -t erc_navigation_sim .` and next executing ` docker run erc_navigation_sim` I get this:
```shell_session
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "source": executable file not found in $PATH: unknown.
ERRO[0002] error waiting for container: context canceled
```

**Comment by bjsowa** [comment]
What's the full `docker run` command you are running?

**Comment by GiuliaB97** [comment]
I tried to run it without arguments as well as to run the complete commands you suggest in the readme file, but nothing change I still get that error.

**Comment by bjsowa** [comment]
What OS are you using? Please paste the output of `uname -a`.
Did you do `xhost +local:root` before running the container?
Could you try the image from Github's package registry? - just replace `erc_navigation_sim` with `ghcr.io/europeanroverchallenge/erc-remote-navigation-sim`

**Comment by GiuliaB97** [comment]
Running  ` uname -a` I get this: 
```shell_session
Linux pc-giulia 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Yes, I run `xhost +local:root` before executing the run command.

If I run: ` docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY --name erc_sim --net=host ghcr.io/europeanroverchallenge/erc-remote-navigation-sim` I can run the container, but Gazebo crashes with the following error:
```shell_session
[gazebo_gui-3] process has died [pid 63, exit code 134, cmd /opt/ros/melodic/lib/gazebo_ros/gzclient __name:=gazebo_gui __log:=/root/.ros/log/d0744cce-c5fb-11eb-9073-7c67a2abd501/gazebo_gui-3.log].
log file: /root/.ros/log/d0744cce-c5fb-11eb-9073-7c67a2abd501/gazebo_gui-3*.log
```

**Comment by bjsowa** [comment]
What GPU are you using? If NVIDIA, did you install the Nvidia Container Toolkit? If not, follow [these instructions](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html). 

Does running `nvidia-smi` on the host output anything?

**Comment by GiuliaB97** [comment]
I am using an NVIDIA GPU and yes, I have already installed the Nvidia Container Toolkit.

The output of the `nvidia-smi` command is this:
```shell_session
Mon Jun  7 18:27:31 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:08:00.0  On |                  N/A |
|  0%   38C    P0    N/A /  90W |    140MiB /  4036MiB |      6%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1070      G   /usr/lib/xorg/Xorg                100MiB |
|    0   N/A  N/A      1280      G   /usr/bin/gnome-shell               36MiB |
+-----------------------------------------------------------------------------+

```

**Comment by bjsowa** [comment]
Try to run the `nvidia-smi` command from a docker container, for example:
```
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
```

**Comment by GiuliaB97** [comment]
Running the first command nothing changes; Gazebo crashes anyway.
On the other hand, if I try to execute the second, nothing happens since I get no log output on the terminal.

**Comment by bjsowa** [comment]
The first command should not even try to run Gazebo, but just show the output of the `nvidia-smi` utility. 

The second command is from [Nvidia Container Toolkit Installation Guide](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html). No output indicates that your installation is broken. I suggest carefully following the guide again and, if that still doesn't work, finding help on the Nvidia forums.

**Comment by GiuliaB97** [comment]
Yes, you are right; since I have tried the commands you wrote on different days I messed up and I forgot to tell you the whole results: `sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi`  returns the same output (or at least quite similar) of this:  `nvidia-smi `. 
In particular, it returns the following output:
 
`
sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Fri Jun 11 10:08:18 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:08:00.0  On |                  N/A |
|  0%   49C    P8    N/A /  90W |    276MiB /  4036MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
It is trying to remove:  `nvidia-smi ` that returns no log-output.


The same happens with the first command: if it is run with the `nvidia-smi ` at the end, the output is the following one:
`
sudo docker run --rm --gpus all ghcr.io/europeanroverchallenge/erc-remote-navigation-sim nvidia-smi
[sudo] password di hologram: 
Fri Jun 11 10:06:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.80       Driver Version: 460.80       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:08:00.0  On |                  N/A |
|  0%   49C    P5    N/A /  90W |    276MiB /  4036MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
`
I am sorry for the inconvenience, I got confused.

**Comment by bjsowa** [comment]
Do you perhaps have hybrid graphics (integrated and dedicated card) on your computer?

**Comment by GiuliaB97** [comment]
No, I have not hybrid graphics and I do not think that the issue is related to the GPU used indeed if I run the following commands:
```shell_session
systemctl start docker
docker pull ghcr.io/europeanroverchallenge/erc-remote-navigation-sim:latest
docker tag ghcr.io/europeanroverchallenge/erc-remote-navigation-sim:latest erc_navigation_sim
xhost +local:root
```
and the following one:
`docker run --rm -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY --name erc_sim -p 11311:11311 erc_navigation`
 with  `-p 11311:11311` instead of `--net=host` Gazebo does not crash and works fine, however, if I try to build the image by myself it still does not work.
